# Note: supported platforms: macOS, Linux and Windows
# Please make sure that's working on all supported platforms
version: "3.9"

services:
#  postgres:
#    image: postgres:12.8-alpine
#    restart: always
#    volumes:
#      - ./../.docker/floship/portal/postgresql/data:/var/lib/postgresql/data:z
#    env_file:
#      - ./.env.dev
  redis:
    image: redis:5.0-alpine
    restart: always
  rabbitmq:
    image: rabbitmq:3.8.14-alpine
    restart: always
#  elasticsearch:
#    image: elasticsearch:2.4.6-alpine
#    restart: always
#  web:
#    build: .
#    restart: always
#    command: pipenv run python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code:z
#    ports:
#      - "8000:8000"
#    env_file:
#      - ./.env
#    depends_on:
#      - postgres
#      - redis
#      - rabbitmq
#      - elasticsearch
