# Generated by Django 4.0.1 on 2022-02-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_player_options_player_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(db_index=True, max_length=64, unique=True, verbose_name='Email address'),
        ),
    ]
