# Generated by Django 4.0.1 on 2022-02-27 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_room_presenter_alter_room_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='presenter',
        ),
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administration_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
