# Generated by Django 4.0.1 on 2022-02-28 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_room_presenter_alter_room_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_room',
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='current_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
