# Generated by Django 4.0.1 on 2022-03-07 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_player_current_room_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
