# Generated by Django 4.0.1 on 2022-04-06 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration_room', to=settings.AUTH_USER_MODEL)),
                ('has_access', models.ManyToManyField(related_name='accessible_rooms', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='current_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
